# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Bump up tx power of BLE radio
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Set default color to white
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=100

# Underglow off by default
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# Turn off underglow when sleeping
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Switch off ext power when underglow is off
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y
